shell = "bash -c '{}'"

[[items]]
file = "~/.config/nvim/lua/config/minibase16.lua"
template = "nvim"
subtemplate = "miniBase16"
rewrite = true

[[items]]
file = "~/.config/wezterm/base16-scheme.toml"
template = "wezterm"
rewrite = true

# [[items]]
# file = "~/.local/share/color-schemes/flavours.colors"
# template = "kde"
# rewrite = true
